// Auto-generated by repack.py. Do not edit by hand — re-runs will overwrite.
const VERSION = 'c484e00';
const CACHE = `taiwan-crop-${VERSION}`;
const PRECACHE = ["index.html", "assets/page-data.json", "assets/60c9445d-64d5-4600-8fc2-be7e2da47944.js", "assets/f740b2a9-f5f5-436f-9ee2-5c88da1a82a5.js", "assets/full_page.avif", "assets/tomato_dashboard.avif", "assets/taoyuan_detail.avif"];

self.addEventListener('install', e => {
  // Take over immediately on first install so cache is populated without a reload.
  self.skipWaiting();
  e.waitUntil(
    caches.open(CACHE).then(c =>
      // Best-effort: don't fail install if one URL 404s.
      Promise.all(PRECACHE.map(u =>
        c.add(new Request(u, { cache: 'reload' })).catch(err =>
          console.warn('[sw] precache miss', u, err))
      ))
    )
  );
});

self.addEventListener('activate', e => {
  e.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k)));
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  // Only manage same-origin requests. Live nongzhidao / weather API stay
  // direct so they always get the freshest data and never hit a stale cache.
  if (url.origin !== self.location.origin) return;
  const isHTML =
    req.destination === 'document' ||
    url.pathname.endsWith('/') ||
    url.pathname.endsWith('.html');

  if (isHTML) {
    // Network-first: every reload pulls the latest HTML (which references the
    // latest hashed asset URLs), cache only as offline fallback.
    e.respondWith((async () => {
      try {
        const res = await fetch(req);
        const copy = res.clone();
        caches.open(CACHE).then(c => c.put(req, copy));
        return res;
      } catch {
        const cached = await caches.match(req);
        if (cached) return cached;
        throw new Error('offline + no cached HTML');
      }
    })());
    return;
  }

  // Assets: cache-first. The cache name includes VERSION, so a new deploy
  // gets a fresh cache and old entries are dropped in activate().
  e.respondWith((async () => {
    const cached = await caches.match(req);
    if (cached) return cached;
    const res = await fetch(req);
    if (res.ok) {
      const copy = res.clone();
      caches.open(CACHE).then(c => c.put(req, copy));
    }
    return res;
  })());
});
